apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-dockerfile-twpy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-dockerfile-twpy
    app.kubernetes.io/part-of: my-app-1234
  name: python-dockerfile-twpy
  namespace: jkopriva-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: python-dockerfile-twpy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: python-dockerfile-twpy
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:6b5c45ed1d5f83185cd18d0676e7ff2a2965c641b0939a36e9c8744eb3533b08
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
